### ISSUE TITLE
Player Vision Issue

### ISSUE THREAD

**Issue by jacobmcollins** [ElijahRW/CS300_TEST#26]
I pulled down the latest version of the master branch with the player vision implemented. The player no longer wraps around when travelling outside the bounds of the map. When I tested going out of bounds to the north the player no longer exists.

**Comment by ElijahRW** [comment]
Ok, I'll do some digging this evening and see if I can't figure out what's up.

**Comment by ElijahRW** [comment]
The issue is fixed. I added an if statement to the 'for' loop (current logic is inefficient but functional. Please look for loopholes to make sure it's fully operational now.
